In [3]:
"""
Numpy基础数据结构

Numpy数组是一个多维数组对象，称为ndarray。由两部分组成
① 实际的数据
② 描述这些数据的元数据

"""

'\nNumpy基础数据结构\n\nNumpy数组是一个多维数组对象，称为ndarray。由两部分组成\n① 实际的数据\n② 描述这些数据的元数据\n\n'

In [17]:
#多维数组 ndarray

import numpy as np

ar = np.array([1,2,3,4,5,6,7])
print(ar)
    #输出数组，注意数组的格式：中括号，元素之间没有逗号。（和列表区分）
print(ar.ndim)
    #输出数组维度的个数（轴数），或者说“秩”维度的数量也称为rank
print(ar.shape)
    #数组的维度，对于n行m列的数组，shape为（n,m）
print(ar.size)
    #数组的元素总数，对于n行m列的数组，元素总数为n*m
print(ar.dtype)
    #数组中元素的类型，类似type()注意了，type()是函数，.dtype是方法
print(ar.itemsize)
    #数组中每个元素的字节大小，int321类型字节为4，float64的字节为8；
    #有空B站，看下《头号玩家》
print(ar.data)
    #包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，
    #所以同城不要使用这个属性
ar  
    #交互方式下输出，会有array（数组）

#数组的基本属性
#①数组的维数称为秩（rank），一维数组的秩为1，二维数组的秩为2，以此类推。
#②在Numpy中，每一个线性的数组称为一个轴（axe5），秩其实是描述轴的数量。
# 比如说，二维数组相当于两个一维数组，其中一个一维数组中每个元素
#又是一个一维数组；所以说一维数组就是Numpy中的轴（axes），第一个轴相当于是
#底层数组，第二个轴是底层数组里的数组。
#而轴的数量 秩，就是数组的维度。


[1 2 3 4 5 6 7]
1
(7,)
7
int32
4


array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#创建数组：array（函数），括号内可以是列表、元祖、数组、生成器等

ar1 = np.array(range(10))   # 整型
print(ar1,type(ar1),ar1.dtype)

ar2 = np.array([1,2,3.14,4,5])  # 浮点型
print(ar2,type(ar2),ar2.dtype)

ar3 = np.array([[1,2,3],('a','b','c')])
print(ar3,ar3.shape,ar3.ndim,ar3.size)

ar4 = np.array([[1,2,3],('a','b','c','d')])
print(ar4,ar4.shape,ar4.ndim,ar4.size)


[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32
[1.   2.   3.14 4.   5.  ] <class 'numpy.ndarray'> float64
[['1' '2' '3']
 ['a' 'b' 'c']] (2, 3) 2 6
[list([1, 2, 3]) ('a', 'b', 'c', 'd')] (2,) 1 2


In [30]:
#创建数组：arange(),类似range(),在给定间隔内返回均匀间隔的值。
print(np.arange(10))   #返回整数
print(np.arange(10.0)) #返回浮点型
print(np.arange(5,12)) #返回5-11，切片
print(np.arange(5.0,12,2))   #步长
print(np.arange(5,12.0,2))   #步长

print(np.arange(10000))
# 如果数组太大而无法打印，Numpy会自动跳过数组的中心部分，并只打印边角


[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11]
[ 5.  7.  9. 11.]
[ 5.  7.  9. 11.]
[   0    1    2 ... 9997 9998 9999]


In [36]:
# 创建数组：linspace():返回在间隔(开始，停止)上计算的num个均匀间隔的样本。

ar1 = np.linspace(2.0,3.0, num=5)
print(ar1,type(ar1))

ar11 = np.linspace(2.0,3.0, num=5)
print(ar11,type(ar11))

ar2 = np.linspace(2.0,3.0, num=5,endpoint=False)
print(ar2,type(ar2))

ar3 = np.linspace(2.0,3.0,num=5,retstep=True)
print(ar3,type(ar3)) 

#numply.linspace(start,stop,num=5,endpoint=True,retstep=False,dtype=None)
# start 起始值
# stop 结束值
# num 生成样本数量，默认为5
# endpoint 如果为真，则停止是最后一个样本。否则，不包括在内，默认值为True\

#retstep 如果为真，返回（样本，步骤），其中步长是样本之间的间距。—>
# 输出为一个包含2个元素的元祖，第一个元素为array，第二个为实际步长


[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'>
[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'>
[2.  2.2 2.4 2.6 2.8] <class 'numpy.ndarray'>
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


In [47]:
# 创建数组 zeros()/  zereos_like()/ones()/onses_like()

ar1 = np.zeros(5)
print(ar1,ar2.dtype)
ar2 = np.zeros((2,2),dtype=np.int)
print(ar2,ar2.dtype)
print('-----------------') 
# numpy.zeros(shape,dtype=float,order='c');返回给定形状和类型的新数组，用零填充。
# shape 数组维度，二维以上需要用（），且输入参数为整数
# dtype 数据类型，默认numpy.float64
# order：是否在存储器中以C或fortran连续（按行或者列方式）存储多维数据

ar3 = np.array([list(range(5)),list(range(5,10))])
print(ar3)
ar4 = np.zeros_like(ar3)
print(ar4)
print('-----------------')
    # 返回具有与给定数组相同的形状和类型的零数组，这里ar4根据ar3的形状和dtyp创建一个全0的数组

ar5 = np.ones(9)
print(ar5)
ar6= np.ones((2,3,4))
print(ar6)
ar7 = np.ones_like(ar3)
print(ar7)

   # ones()/ ones_like()//zero_like()一样，只是填充为1；

[0. 0. 0. 0. 0.] int32
[[0 0]
 [0 0]] int32
-----------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
-----------------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
# 创建数组：eye()
print(np.eye(5))
    #创建一个正方形的N*N的单位矩阵，对角线值为1，其余为0；

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
'''
ndarray的数据类型

bool 用一个字节存储的布尔类型（True或False）

inti 由所在平台决定其大小的整数（一般为int32或int64）

int8 一个字节大小，-128 至 127

int16 整数，-32768 至 32767

int32 整数，-2 ** 31 至 2 ** 32 -1

int64 整数，-2 ** 63 至 2 ** 63 - 1

uint8 无符号整数，0 至 255

uint16 无符号整数，0 至 65535

uint32 无符号整数，0 至 2 ** 32 - 1

uint64 无符号整数，0 至 2 ** 64 - 1

float16 半精度浮点数：16位，正负号1位，指数5位，精度10位

float32 单精度浮点数：32位，正负号1位，指数8位，精度23位

float64或float 双精度浮点数：64位，正负号1位，指数11位，精度52位

complex64 复数，分别用两个32位浮点数表示实部和虚部

complex128或complex 复数，分别用两个64位浮点数表示实部和虚部
'''

'\nndarray的数据类型\n\nbool 用一个字节存储的布尔类型（True或False）\n\ninti 由所在平台决定其大小的整数（一般为int32或int64）\n\nint8 一个字节大小，-128 至 127\n\nint16 整数，-32768 至 32767\n\nint32 整数，-2 ** 31 至 2 ** 32 -1\n\nint64 整数，-2 ** 63 至 2 ** 63 - 1\n\nuint8 无符号整数，0 至 255\n\nuint16 无符号整数，0 至 65535\n\nuint32 无符号整数，0 至 2 ** 32 - 1\n\nuint64 无符号整数，0 至 2 ** 64 - 1\n\nfloat16 半精度浮点数：16位，正负号1位，指数5位，精度10位\n\nfloat32 单精度浮点数：32位，正负号1位，指数8位，精度23位\n\nfloat64或float 双精度浮点数：64位，正负号1位，指数11位，精度52位\n\ncomplex64 复数，分别用两个32位浮点数表示实部和虚部\n\ncomplex128或complex 复数，分别用两个64位浮点数表示实部和虚部\n'

In [58]:
#作业1：分别按照要求，生成一个一维数组、二维数组，并且查看其shape

import numpy as np

ar= np.array([1,2,'a','hello',[1,2,3],{'two':200,'oen':100} ])
print(ar)
print(ar.shape)

ar2 =np.array([['0','1','2','3','4','5'],['a','b','c','d','e','f'],['True','False','True','Fasle','True','Ture']])
print(ar2)
print(ar2.shape)


[1 2 'a' 'hello' list([1, 2, 3]) {'two': 200, 'oen': 100}]
(6,)
[['0' '1' '2' '3' '4' '5']
 ['a' 'b' 'c' 'd' 'e' 'f']
 ['True' 'False' 'True' 'Fasle' 'True' 'Ture']]
(3, 6)


In [61]:
#作业2：生成一个一维数组，起始值为5，终点值为15，样本数为10个

ar=np.arange(5,15)
print(ar)

[ 5  6  7  8  9 10 11 12 13 14]


In [68]:
#作业3：按照要求创建以下数组
    #思考，除了用np.array直接创建，能否根据规则创建；
    
print(np.zeros((4,4)),'\n..............')
print(np.ones((2,3)),'\n...............')

print(np.eye((3)),'\n...............')


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
..............
[[1. 1. 1.]
 [1. 1. 1.]] 
...............
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
...............
