In [1]:
#基本索引和切片

import numpy as np


In [7]:
ar = np.arange(20)
print(ar)
print(ar[4])
print(ar[:3])
print(ar[::2])
    #一维数组类似list

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[0 1 2]
[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
ar = np.arange(16).reshape(4,4)
print(ar)
print(ar[2])
    #取行
print(ar[2][2])
    # 取第3行第3个列

print(ar[1:3])
    #取第2、3行；

print(ar[2,2])
print('----------'*10)
print(ar[:2,2:])
    #二维数组索引

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]
10
[[ 4  5  6  7]
 [ 8  9 10 11]]
10
----------------------------------------------------------------------------------------------------
[[2 3]
 [6 7]]


In [22]:
#三维数组
ar = np.arange(12).reshape(3,2,2)
print(ar)
print(ar[2][1][0])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
10


In [32]:
# 布尔型索引及切片
    #判断&索引

ar = np.arange(12).reshape(3,4)
print(ar)

i = np.array([True,False,True])
j = np.array([True,True,False,False])
print(i)
print(j)

print(ar[i,:])  # 第一三行
print(ar[ :,j])

print(ar>5,type(ar>5))
print(ar[ar>5])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]
[ True  True False False]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]] <class 'numpy.ndarray'>
[ 6  7  8  9 10 11]


In [39]:
# 索引值的更改及复制

ar = np.arange(10)
print(ar)

ar[5]=100
ar[7:9]=200
print(ar)
 #一个标量赋值给一个索引/切片时，会自动改变/传播原始数组
    
ar = np.arange(10)
b =ar.copy()
b[7:9]=200
print(ar)
print(b)
    # 复制


[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 200 200   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]


In [40]:
"""

【课程1.4  Numpy索引及切片】 课程作业
	作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少
 
"""

'\n\n【课程1.4  Numpy索引及切片】 课程作业\n\uf06e\t作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少\n \n'

In [45]:
ar =np.arange(25).reshape(5,5)
print(ar)

print(ar[4])

print(ar[:2,3:])

print(ar[3][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [50]:
#	作业2：按照要求创建数组，筛选出元素值大于5的值并生成新的数组

ar =np.arange(10).reshape(2,5)
print(ar)

print(ar>5)

print(ar[ar>5])

b =ar[ar>5]
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[False False False False False]
 [False  True  True  True  True]]
[6 7 8 9]
[6 7 8 9]
