In [1]:
"""
Numpy通用函数
基本操作
"""

'\nNumpy通用函数\n基本操作\n'

In [8]:
# 数组形状 .T/reshape() / .resize()
import numpy as np
ar1=np.arange(10)
print(ar1,'\n',ar1.T)

ar2= np.ones((5,2))
print(ar2,'\n',ar2.T)
# .T方法：转置，例如原shape为(3,4)/(4,3,2)
        # --->所以一维数组转置后结果不变。




[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
ar3 = ar1.reshape(2,5)
print(ar1,'\n',ar3)

ar4 = np.zeros((4,6)).reshape(3,8)
print(ar4)

[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
#作业1：创建一个20个元素的数组，分别改变成两个形状：(4,5),(5,6) （提示：超出范围用resize）

ar1 =np.arange(20)

ar2=ar1.reshape(4,5)
print(ar2)
print('................')

print(np.resize(ar1,(5,6)), '\n-------')

   #    resize:给定一个数组，和特定维度，将会返回一个给定维度形式的新数组。
    #   如果新数组比原数组大，则将会copy原数组中的值对新数组进行填充

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
................
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]] 
-------


In [33]:
#作业2：创建一个(4,4)的数组，把其元素类型改为字符型
ar =np.arange(16).reshape(4,4)
print(ar)

    #字符类型修改，不会



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [29]:
#作业3：根据要求创建数组，运用数组的运算方法得到结果：result = ar * 10 +100，并求出result的均值及求和

ar =np.arange(16).reshape(4,4)
print(ar)
print('--'*20)
ar2= ar*10+100
print(ar2)
print('--'*20)
print(ar2.sum())   #数组求和

    
print(ar2.mean())   # 数组平均值

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------------
[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
----------------------------------------
2800
175.0
