In [3]:
import numpy as np

t1 = np.arange(12)
t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
t1.shape

(12,)

In [7]:
t2=np.array([[1,2,3],[4,5,6]])
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
t2.shape

(2, 3)

In [11]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,13]]])
t3               

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 13]]])

In [12]:
t3.shape

(2, 2, 3)

In [16]:
t4 =np.arange(12)
t4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
t4.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
t5 = np.arange(24).reshape(2,3,4)
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
t5.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
t5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
t5 = t5.reshape((4,6))

In [32]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
t5.reshape((24,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
t5.reshape((24,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [36]:
t5.reshape((1,24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
t5.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
"""
数组的形状
reshape()  不改变原值

flatten   展开为一维数组
"""

'\nreshape()  不改变原值\n\nflatten   展开为一维数组\n'

In [39]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
t5+2
    #数组内所有元素+2；

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [41]:
t5*2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [42]:
t5/0

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [44]:
"""
nan   not a number
inf   infinite无限无穷

"""

'\nnan   not a number\ninf   infinite无限无穷\n\n'

In [45]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
t6 = np.arange(100,124).reshape((4,6))
t6

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123]])

In [49]:
t6+t5

array([[100, 102, 104, 106, 108, 110],
       [112, 114, 116, 118, 120, 122],
       [124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146]])

In [52]:
t7 =np.arange(0,6)
t7

array([0, 1, 2, 3, 4, 5])

In [53]:
t5


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [54]:
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [57]:
t8 =np.arange(4).reshape((4,1))
t8


array([[0],
       [1],
       [2],
       [3]])

In [58]:
t5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [56]:
t5-t8

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [60]:
t9 =np.arange(10)
t9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
t5-t9

ValueError: operands could not be broadcast together with shapes (4,6) (10,) 

In [63]:
'''
数组和数组的计算

    # 某行或某列一致时，可以计算；
'''
    

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-63-00c0d94c83bd>, line 6)

In [ ]:
'''
ipython 使用方法】】
【·】安装的Anaconda中包含了IPython，因此不需要再而外安装，接下来演示IPython的使用，进入控制台（【win+r】，输入cmd），
并在控制台中输入命令“ipython”，运行结果如下图所示：
'''

In [64]:
'''
numpy 索引和切片
'''

'\nnumpy 索引和切片\n'

In [19]:
t5

array([2])