In [4]:
'''
Pandas数据结构DataFrame：基本概念及创建
二维数组 DataFrame是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。
DataFrame中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。

'''

'\nPandas数据结构Dataframe：基本概念及创建\n二维数组 DataFrame是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。\nDataFrame中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。\n\n'

In [5]:
import numpy as np
import pandas as pd

In [17]:
# DataFrame 数据结构
# DataFrame 是一个表格型的数据结构，“带有标签的二维数组”
# DataFrame 带有inex（行标签） 和columns（列标签）


data = {'name':['Jack','Tom',"Marry"],
        'age':[18,19,20],'grender':['m','m','w']}
frame = pd.DataFrame(data)
print(frame)
print(type(frame))

print(frame.index,'该数据类型为：',type(frame.index))
print(frame.columns,'该数据类型为：',type(frame.columns))
print(frame.values,'该数据类型为：',type(frame.values))
    #查看数据，数据类型为DataFrame
    # .index 查看行标签
    # .columns 查看列标签
    # .values 查看值，数据类型为ndarray


    name  age grender
0   Jack   18       m
1    Tom   19       m
2  Marry   20       w
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 该数据类型为： <class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'grender'], dtype='object') 该数据类型为： <class 'pandas.core.indexes.base.Index'>
[['Jack' 18 'm']
 ['Tom' 19 'm']
 ['Marry' 20 'w']] 该数据类型为： <class 'numpy.ndarray'>


In [27]:
# DataFrame 创建方法一： 由数组/list组成的字典
# 创建方法：pandas.DataFrame()

data1 = {'a':[1,2,3],'b':[3,4,5],'c':[5,6,7]}
print(data1)
df1=pd.DataFrame(data1)
print(df1)
print('--------------------分割线-----------------------')
data2 = {'one':np.random.rand(3),'two':np.random.rand(3)}   # 不懂columns 必须相同数量值
print(data2)
df2=pd.DataFrame(data2)
print(df2)
    # 由数组/list组成的字典，创建DataFrame ，columns为字典key，index为默认数字标签
    # 字典的值的长度必须保持一致！
print('--------------------分割线-----------------------')
df1 = pd.DataFrame(data1,columns=['a','b','c','d'])
print(df1)
print('--------------------分割线-----------------------')
df1 = pd.DataFrame(data1,columns=['b','c'])
print(df1)
    # columns参数，可以重新制定列的顺序，格式为list，如果现有数据中没有该列（比如d），则产生NaN值；
    # columns重新制定时，列的数量可以少于原数据
print('--------------------分割线4-----------------------')

df2 = pd.DataFrame(data2,index =['f1','f2','f3'])
print(df2)
    # index参数，重新定义index,格式为list,长度必须保持一致。
    

{'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
   a  b  c
0  1  3  5
1  2  4  6
2  3  5  7
--------------------分割线-----------------------
{'one': array([0.50821452, 0.7820953 , 0.91382488]), 'two': array([0.54864507, 0.9694734 , 0.70961345])}
        one       two
0  0.508215  0.548645
1  0.782095  0.969473
2  0.913825  0.709613
--------------------分割线-----------------------
   a  b  c    d
0  1  3  5  NaN
1  2  4  6  NaN
2  3  5  7  NaN
--------------------分割线-----------------------
   b  c
0  3  5
1  4  6
2  5  7
--------------------分割线4-----------------------
         one       two
f1  0.508215  0.548645
f2  0.782095  0.969473
f3  0.913825  0.709613


In [31]:
# DataFrame 创建方法二： 由Series组成的字典

data1 = {'one':pd.Series(np.random.rand(2)),'two':pd.Series(np.random.rand(3))}
print(data1)
df1 = pd.DataFrame(data1)
print(df1)
print('-------------------------fgx------------------')

data2 = {'one':pd.Series(np.random.rand(2),index=['a','b']),
         'two':pd.Series(np.random.rand(3),index=['a','b','c'])}
print(data2)
df2 = pd.DataFrame(data2)
print(df2)
    # 由Series组成的字典，创建DataFrame，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
    # Series可以长度不一样，生成的DataFrame会出现NaN值

{'one': 0    0.598472
1    0.585149
dtype: float64, 'two': 0    0.448015
1    0.180315
2    0.515393
dtype: float64}
        one       two
0  0.598472  0.448015
1  0.585149  0.180315
2       NaN  0.515393
-------------------------fgx------------------
{'one': a    0.314499
b    0.418558
dtype: float64, 'two': a    0.728723
b    0.712972
c    0.735729
dtype: float64}
        one       two
a  0.314499  0.728723
b  0.418558  0.712972
c       NaN  0.735729


In [39]:
# DataFrame 创建方法三：通过二维数组直接创建

ar = np.random.rand(9).reshape(3,3)
print(ar)
df1=pd.DataFrame(ar)
print(df1)

df2=pd.DataFrame(ar,index=['a','b','c'],columns=['one','two','three'])
print(df2)
    # 通过二维数组直接创建DataFrame，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
    # index和columns 指定长度与原数据保持一致

[[0.96100332 0.67810509 0.24576513]
 [0.20628872 0.6809652  0.21918307]
 [0.12449281 0.82415361 0.87981196]]
          0         1         2
0  0.961003  0.678105  0.245765
1  0.206289  0.680965  0.219183
2  0.124493  0.824154  0.879812
        one       two     three
a  0.961003  0.678105  0.245765
b  0.206289  0.680965  0.219183
c  0.124493  0.824154  0.879812


In [44]:
# DataFrame 创建方法四：由字典组成的列表

data=[{'one':1,"two":2},{'one':5,'two':10,'three':20}]
print(data)
df1=pd.DataFrame(data)
print(df1)

df2=pd.DataFrame(data,index=['a','b'])
print(df2)

df3= pd.DataFrame(data,columns=['one','two'])
print(df3)
    # 由字典组成的列表创建DataFrame，columns为字典的key，index不做指定则为默认数组标签
    # columns 和 index 参数分别重新制定相应列及行标签
    

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
   one  three  two
0    1    NaN    2
1    5   20.0   10
   one  three  two
a    1    NaN    2
b    5   20.0   10
   one  two
0    1    2
1    5   10


In [47]:
# DataFrame 创建方法五：由字典组成的字典

data = {'Jack':{'math':90,'english':89,'art':78},
        'Marry':{'math':83,'english':95,'art':92},
        'Tom':{'math':78,'english':67}}

df1 = pd.DataFrame(data)
print(df1)
    #由字典组成的字典创建DataFrame，columns为字典的key，index为子字典的key
df2 = pd.DataFrame(data,columns =['Jack','Tom','Bob'])
df3 = pd.DataFrame(data,index =['a','b','c'])
print(df2)
print(df3)
    # columns参数可以增加和减少现有列，如出现新的列，值为NaN
    # index 在这里和之间不同，并不能改变原有index，如果指向新的标签，值为NaN（非常重要）



         Jack  Marry   Tom
art        78     92   NaN
english    89     95  67.0
math       90     83  78.0
         Jack   Tom  Bob
art        78   NaN  NaN
english    89  67.0  NaN
math       90  78.0  NaN
   Jack  Marry  Tom
a   NaN    NaN  NaN
b   NaN    NaN  NaN
c   NaN    NaN  NaN


In [52]:
# 作业1：用四种不同的方法，创建以下Dataframe（保证columns和index一致，值不做要求）

#方法1  由数组列表组成的字典创建DataFrame

data1 = {'one':[1,2,3,4,5],'two':[2,3,4,5,6],'three':[3,4,5,6,7],'four':[4,5,6,7,8]}
print(data1)
df1=pd.DataFrame(data1)
print(df1)
df2 = pd.DataFrame(data1,index =['a','b','c','d','e'],columns=['four','one','three','two'])
print(df2)




{'one': [1, 2, 3, 4, 5], 'two': [2, 3, 4, 5, 6], 'three': [3, 4, 5, 6, 7], 'four': [4, 5, 6, 7, 8]}
   one  two  three  four
0    1    2      3     4
1    2    3      4     5
2    3    4      5     6
3    4    5      6     7
4    5    6      7     8
   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6


In [62]:
#方法2:由Series组成的字典


data = {'one':pd.Series(np.random.rand(5),index=['a','b','c','d','e']),
        'two':pd.Series(np.random.rand(5),index=['a','b','c','d','e']),
        'three':pd.Series(np.random.rand(5),index=['a','b','c','d','e']),
        'four':pd.Series(np.random.rand(5),index=['a','b','c','d','e'])}
df1=pd.DataFrame(data)
print(df1)


        one       two     three      four
a  0.933387  0.173397  0.799569  0.299086
b  0.631715  0.847021  0.298100  0.266711
c  0.381337  0.548610  0.665023  0.504664
d  0.667255  0.121870  0.522442  0.898146
e  0.253710  0.962665  0.138702  0.097342


In [64]:
#方法三：通过二维数组直接创建

ar = np.random.rand(20).reshape(5,4)
print(ar)
df1=pd.DataFrame(ar)
print(df1)

df2=pd.DataFrame(ar,index=['a','b','c','d','e'],columns=['one','two','three','four'])
print(df2)

[[0.61222744 0.78605641 0.82264612 0.03447133]
 [0.17405401 0.8100513  0.44471717 0.25425735]
 [0.99550968 0.76122152 0.87669246 0.56487948]
 [0.18353376 0.38105031 0.0013959  0.99189963]
 [0.69720182 0.8854286  0.46347198 0.17183764]]
          0         1         2         3
0  0.612227  0.786056  0.822646  0.034471
1  0.174054  0.810051  0.444717  0.254257
2  0.995510  0.761222  0.876692  0.564879
3  0.183534  0.381050  0.001396  0.991900
4  0.697202  0.885429  0.463472  0.171838
        one       two     three      four
a  0.612227  0.786056  0.822646  0.034471
b  0.174054  0.810051  0.444717  0.254257
c  0.995510  0.761222  0.876692  0.564879
d  0.183534  0.381050  0.001396  0.991900
e  0.697202  0.885429  0.463472  0.171838


In [69]:
#方法四：由字典组成的列表

data=[{'one':1,"two":2,'three':56,'four':78},
      {'one':5,'two':10,'three':20,'four':78},
      {'one':15,'two':20,'three':50,'four':88},
      {'one':55,'two':17,'three':27,'four':74},
      {'one':85,'two':19,'three':23,'four':58}]
print(data)
df1=pd.DataFrame(data)
print(df1)

df2=pd.DataFrame(data,index=['a','b','c','d','e'])
print(df2)


[{'one': 1, 'two': 2, 'three': 56, 'four': 78}, {'one': 5, 'two': 10, 'three': 20, 'four': 78}, {'one': 15, 'two': 20, 'three': 50, 'four': 88}, {'one': 55, 'two': 17, 'three': 27, 'four': 74}, {'one': 85, 'two': 19, 'three': 23, 'four': 58}]
   four  one  three  two
0    78    1     56    2
1    78    5     20   10
2    88   15     50   20
3    74   55     27   17
4    58   85     23   19
   four  one  three  two
a    78    1     56    2
b    78    5     20   10
c    88   15     50   20
d    74   55     27   17
e    58   85     23   19


In [72]:
# 方法五：由字典组成的字典

data = {'one':{'a':90,'b':89,'c':78,'d':90,'e':98},
        'two':{'a':83,'b':95,'c':92},
        'tree':{'a':78,'b':67},
        'four':{'a':78,'b':67}}

df1 = pd.DataFrame(data)
print(df1)


   one   two  tree  four
a   90  83.0  78.0  78.0
b   89  95.0  67.0  67.0
c   78  92.0   NaN   NaN
d   90   NaN   NaN   NaN
e   98   NaN   NaN   NaN
