In [1]:
500/12

41.666666666666664

In [13]:
500/365*5*10

68.4931506849315

In [38]:
from numpy import * 


arr2d=array([[1,2,3],[4,5,6]])


print(arr2d)



[[1 2 3]
 [4 5 6]]


In [46]:
s= arr2d[:2, 2]
print(s)

[3 6]


In [49]:
s2= array([[2],[2]])
print(s2)

[[2]
 [2]]


In [44]:
from numpy import * 

b =array([[3],[6]])
print(b)

[[3]
 [6]]


In [35]:
s1 =arr2d([[2][2]])

IndexError: list index out of range

In [26]:
import array
#array模块是python中实现的一种高效的数组存储类型。它和list相似，但是所有的数组成员必须是同一种类型，在创建数组的时候，就确定了数组的类型

#array.array(typecode,[initializer]) --typecode:元素类型代码；initializer:初始化器，若数组为空，则省略初始化器
arr = array.array('i',[0,1,1,3])
print(arr)


array('i', [0, 1, 1, 3])


In [36]:
from numpy import * 
 
a=array([[1,2],[2,3]])
a.ndim
print(a)

[[1 2]
 [2 3]]


TypeError: data type not understood

In [ ]:
是array([3, 6]) 而不是array([3],[6])